config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'about',   to: 'static_pages#about'
  get 'signup',  to: 'users#new'

  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :email_resets,        only: [:new, :create, :edit, :update]

  get  'home',                     to: 'users#home'
  scope '/settings' do
    get  'profile',                to: 'users#profile'
    get  'account',                to: 'users#account' 
    get  'confirm_delete_account', to: 'users#confirm_delete_account'
    post 'change_password',        to: 'users#change_password'
    post 'delete_account',         to: 'users#delete_account'
    get  'rhisomas',               to: 'territories#list'
    get  'edit_rhisoma/:id',       to: 'territories#edit'
  end

  resources :territories
  patch '/nodes/position', to: 'nodes#bulk_update_pos'
  resources :nodes
  resources :edges
  post '/territories/:id/clone', to: 'territories#clone'

  resources :styling_groups

  get '/.well-known/acme-challenge/:id' => 'sessions#temp'
  get '/fake_logout' => 'sessions#fake_destroy'
end

app/controllers/email_resets_controller.rb
# The email resets controller is similar to the password resets controller,
# but it handles email alteration logic.
# 
# @author João Mateus de Freitas Veneroso
# @since 0.1.0
class EmailResetsController < ApplicationController
  # The user must be logged in to request an email change, but since
  # the update action requests the user password there is no 
  # need to require the user to be logged in during edit and update.
  before_action :logged_in_user,   only: [:new, :create]
  before_action :get_user,         only: [:edit, :update]
  before_action :valid_user,       only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  # Renders the email change request view.
  # @route GET /emails_resets/new
  def new
    @user = current_user
  end

  # Creates a new email change request. The new email address must be properly
  # checked before it is activated, so a request message is sent to the new
  # email address.
  # @route POST /emails_resets/new
  # @route_param email_reset [new_email]
  def create
    @user = current_user
    # The new email is stored in the database so we can make sure it is 
    # a valid address when the change is confirmed.
    @user[:new_email] = params[:email_reset][:new_email].downcase
    if @user.save
      @user.create_email_reset_digest
      @user.send_email_reset_email
      flash[:info] = t :email_reset_sent
      redirect_to account_path
    else 
      render 'new'
    end
  end

  # Renders the email change confirmation view.
  # @route GET /emails_resets/$(email_reset_token)/edit
  # @route_param email
  def edit
  end

  # Confirms the email change.
  # @route PATCH /emails_resets/$(email_reset_token)
  # @route_param user [email]
  # @route_param user [password]
  def update
    if @user.authenticated?(:password, params[:user][:password])
      @user.email = @user.new_email
      if @user.save
        @user.update_attribute(:new_email, nil)
        @user.update_attribute(:email_reset_digest, nil)
        flash[:success] = t :email_updated 
        log_in @user
      else
        flash[:danger] = t :invalid_email_info
      end
      redirect_to home_path and return
    else
      @user.errors.add(:base, t(:wrong_password))
    end
    render 'edit'
  end

  private

    # Before filter that confirms the user is logged-in.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = t :please_log_in
        redirect_to login_url
      end
    end

    # Before filter that finds user by email.
    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Before filter that confirms the email reset token is valid.
    def valid_user
      unless @user
        flash[:danger] = t :invalid_user
        redirect_to root_url
        return
      end

      unless @user.activated
        flash[:danger] = t :user_not_activated
        redirect_to root_url
        return
      end

      unless @user.authenticated?(:email_reset, params[:id])
        flash[:danger] = t :invalid_email_reset_token
        redirect_to root_url
      end
    end

    # Before filter that checks the expiration of the email reset token.
    def check_expiration
      if @user.email_reset_expired?
        flash[:danger] = t :email_reset_expired
        redirect_to home_path
      end
    end
end

app/views/email_resets/edit.html.erb
<% provide(:page_title, 'Change email') %>

<% content_for :errors do %>
  <%= render 'shared/error_messages' %>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">Change Email</div>
      <div class="panel-body">
        <%= form_for(@user, url: email_reset_path(params[:id])) do |f| %>
          <%= label_tag :email %>
          <%= text_field_tag :email, @user.email, readonly: true, class: 'form-control' %>

          <%= f.label :new_email %>
          <%= f.text_field :new_email, value: @user.new_email, readonly: true, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.submit "Update email", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/email_resets/new.html.erb
<% provide(:page_title, 'Change email') %>

<% content_for :errors do %>
  <%= render 'shared/error_messages' %>
<% end %>

<% content_for :css do %>
  <%= stylesheet_link_tag 'system.css' %>
<% end %>

<script>
$.ajax({
    url: "/language-pt.json",
    type: "GET",
    contentType: 'application/json; charset=utf-8',
    success: function (resultData) {
        var locales_data = resultData;
        main(locales_data);
    },
    error: function (jqXHR, textStatus, errorThrown) {
    },
    timeout: 120000,
});

function main(locales_data){
  var gui = new Gui();
  var top_menu = new SystemGui();
  top_menu.setLocales(locales_data);
  top_menu.setSearch(false);
  top_menu.drawSystemMenu();

  var sidebar = {id:"system-sidebar",class:"system-sidebar",height:window.innerHeight-40};
  gui.addContainer(sidebar);

  var profile_button = {id:"system-profile-button",class:"system-sidebar-primary-button",top:150};
  gui.addLink(profile_button,"system-sidebar");
  gui.addText("system-profile-button","PERFIL");
  document.getElementById("system-profile-button").setAttribute('href',"/settings/profile");

  var account_button = {id:"system-account-button",class:"system-sidebar-primary-button",top:200,backgroundColor:"rgb(30,30,30)",color:"white"};
  gui.addField(account_button,"system-sidebar");
  gui.addText("system-account-button",'CONTA');

  var change_password_button = {id:"system-change-password-button",class:"system-sidebar-secondary-button-inactive",top:250};
  gui.addLink(change_password_button,"system-sidebar");
  gui.addText("system-change-password-button","TROCAR SENHA");
  document.getElementById("system-change-password-button").setAttribute('href',"/settings/account");

  var change_email_button = {id:"system-change-email-button",class:"system-sidebar-secondary-button-active",top:280};
  gui.addField(change_email_button,"system-sidebar");
  gui.addText("system-change-email-button","TROCAR EMAIL");

  var delete_account_button = {id:"system-delete-account-button",class:"system-sidebar-secondary-button-inactive",top:310};
  gui.addLink(delete_account_button,"system-sidebar");
  gui.addText("system-delete-account-button","DELETAR CONTA");
  document.getElementById("system-delete-account-button").setAttribute('href',"/settings/confirm_delete_account");

  var rhisomas_button = {id:"system-rhisomas-button",class:"system-sidebar-primary-button",top:340};
  gui.addLink(rhisomas_button,"system-sidebar");
  gui.addText("system-rhisomas-button","RHISOMAS");
  document.getElementById("system-rhisomas-button").setAttribute('href',"/settings/rhisomas");

  var change_email_container = {id:"system-change-email",width:258,height:98,top:(window.innerHeight-160)/2,left:(window.innerWidth-320-320)/2+320,backgroundColor:"white",padding:30,border:"1px solid #aeaeae",boxshadow:"-5px 5px #aeaeae"};
  gui.addContainer(change_email_container);

  var form_label = {id:"system-label",class:"form-label",width:298};
  gui.addField(form_label,"system-change-email");
  gui.addText("system-label",'MUDAR EMAIL');
  document.getElementById("system-label").style.textAlign = "center";

  var form = document.createElement("form");
  form.setAttribute('method',"post");
  form.setAttribute('action',"/email_resets");
  form.setAttribute('accept-charset',"UTF-8");

  var general_input = document.createElement("input");
  general_input.setAttribute('type',"hidden");
  general_input.setAttribute('name',"utf8");
  general_input.setAttribute('value',"✓");

  var auth_input = document.createElement("input");
  auth_input.setAttribute('type',"hidden");
  auth_input.setAttribute('name',"authenticity_token");
  auth_input.setAttribute('value','<%= form_authenticity_token %>');

  var email_input = document.createElement("input");
  email_input.setAttribute('type',"email");
  email_input.setAttribute('name',"email_reset[new_email]");
  email_input.setAttribute('id',"email_reset_new_email");
  email_input.setAttribute('class',"form-control");
  email_input.setAttribute('placeholder',"E-mail");

  var submit_button = document.createElement("input");
  submit_button.setAttribute('type',"submit");
  submit_button.setAttribute('name',"commit");
  submit_button.setAttribute('data-disable-with',"ATUALIZAR EMAIL");
  submit_button.setAttribute('class',"button-right");
  submit_button.setAttribute('id',"submit-button");
  submit_button.setAttribute('value',"ATUALIZAR EMAIL");
  submit_button.style.width = document.getElementById("system-change-email").offsetWidth+"px";
  submit_button.style.left = "-1px";
  submit_button.style.top = document.getElementById("system-change-email").offsetHeight-42-1+"px";

  form.appendChild(general_input);
  form.appendChild(auth_input);
  form.appendChild(email_input);
  form.appendChild(submit_button);

  document.getElementById('system-change-email').appendChild(form);
}
  

</script>