config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'about',   to: 'static_pages#about'
  get 'signup',  to: 'users#new'

  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :email_resets,        only: [:new, :create, :edit, :update]

  get  'home',                     to: 'users#home'
  scope '/settings' do
    get  'profile',                to: 'users#profile'
    get  'account',                to: 'users#account' 
    get  'confirm_delete_account', to: 'users#confirm_delete_account'
    post 'change_password',        to: 'users#change_password'
    post 'delete_account',         to: 'users#delete_account'
    get  'rhisomas',               to: 'territories#list'
    get  'edit_rhisoma/:id',       to: 'territories#edit'
  end

  resources :territories
  patch '/nodes/position', to: 'nodes#bulk_update_pos'
  resources :nodes
  resources :edges
  post '/territories/:id/clone', to: 'territories#clone'

  resources :styling_groups

  get '/.well-known/acme-challenge/:id' => 'sessions#temp'
  get '/fake_logout' => 'sessions#fake_destroy'
end

app/models/user.rb
# The user model stores all authentication and user account data.
# 
# @author João Mateus de Freitas Veneroso
# @since 0.1.0
class User < ApplicationRecord
  # These tokens represent the unhashed version of a digest stored
  # in the database.
  attr_accessor :remember_token, :activation_token, 
                :reset_token, :email_reset_token

  has_many :territories, dependent: :destroy
  has_many :styling_groups, dependent: :destroy
  has_many :nodes, through: :territories
  has_many :edges, through: :territories

  # This regex is not 100% guaranteed because email addresses may contain 
  # all sorts of unusual characters but it is good enough for 99.9% of 
  # the cases.
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validate  :is_new_email_valid

  # All emails are converted to downcase before storing at the database.
  before_save :downcase_email
  before_create :create_activation_digest

  has_secure_password

  class << self
    # Returns the hash digest of the given string using the bcrypt 
    # hash function.
    # @param string [String] the string to convert.
    # @return [String] the hash digest.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    # @return [String] random string.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  # @return [void]
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user.
  # @return [void]
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest. This function
  # can authenticate email reset, password reset, activation 
  # and session digests.
  # @param [Symbol] `reset_email`, `reset_password`, `activation` or `remember`
  # @return [Boolean]
  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    password = BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates an account.
  # @return [void]
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  # @return [void]
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  # @return [void]
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), 
                   reset_sent_at: Time.zone.now)
  end

  # Sends password reset email.
  # @return [void]
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Sends email reset email.
  # @return [void]
  def send_email_reset_email
    UserMailer.email_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  # @return [Boolean]
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Creates email reset digest.
  # @return [void]
  def create_email_reset_digest
    self.email_reset_token = User.new_token
    update_columns(email_reset_digest: User.digest(email_reset_token), 
                   email_reset_sent_at: Time.zone.now)
  end

  # Sends email reset confirmation message.
  # @return [void]
  def send_email_reset_email
    UserMailer.email_reset(self).deliver_now
  end

  # Returns true if an email reset has expired.
  # @return [Boolean]
  def email_reset_expired?
    email_reset_sent_at < 2.hours.ago
  end

  def graph
    { nodes: self.nodes, edges: self.edges }
  end

  def main_territory
    territory = self.territories.where(main: true).first
    if territory.nil?
      self.territories.first
    else 
      return territory
    end
  end

  private

    # Converts email to all lower-case.
    # @return [String] the downcased email.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    # @return [void]
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    # Validates a new email address with the same rules valid for the 
    # email column.
    def is_new_email_valid
      if new_email.present? 
        is_valid = (VALID_EMAIL_REGEX =~ new_email).nil?
        is_unique = User.find_by(email: new_email)
 
        errors.add(:new_email, "is too long")       if new_email.length > 255
        errors.add(:new_email, "is invalid")        if is_valid
        errors.add(:new_email, "is already taken")  if is_unique
      end
    end
end

app/controllers/users_controller.rb
# The user controller handles user creation logic and user settings
# management.
# 
# @author João Mateus de Freitas Veneroso
# @since 0.1.0
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:new, :create]
  before_action :correct_user,   only:   [:edit, :update]
  before_action :admin_user,     only:   [:index, :show, :destroy]

  layout "home", only: [:home]
 
  # Renders all users in a paginated list. This route is only accessible
  # by the site admin.
  # @route GET /users
  def index
    @users = User.order(:id).paginate(page: params[:page])
  end

  # Renders the user creation view.
  # @route GET /users/new
  def new
    @user = User.new
  end

  # Not used yet.
  # @route GET /users/show/$(id)
  def show
    @user = User.find(params[:id])
  end

  # Creates a new user and sends an activation email.
  # @route POST /users
  # @route_param user [email]
  # @route_param user [password]
  # @route_param user [password_confirmation]
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email

      # Creates the first territory for a user.
      @territory = Territory.new({ name: "Untitled" })
      @territory.user = @user
      @territory.save

      flash[:info] = t :check_email_to_activate_account
      redirect_to root_url
    else
      render 'new'
    end
  end

  # Updated user information.
  # @route PATCH /users/$(id)
  # @route_param user [name]
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = t :profile_updated
      redirect_to profile_path
    else
      render 'users/profile'
    end
  end

  # Destroys a user. This route is only accessible by the site admin.
  # @route DELETE /users/$(id)
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = t :user_deleted
    redirect_to users_url
  end

  # Renders the graph if the user is logged in.
  # @route GET /home
  def home
    @user = current_user
  end

  # Settings.

  # Renders the profile settings if the user is logged in.
  # @route GET /settings/profile
  def profile
    @user = current_user
  end

  # Renders the account settings if the user is logged in.
  # @route GET /settings/account
  def account
    @user = current_user
  end

  # Changes the current user's password if the old password is correct.
  # The password is requested to prevent password changes if the
  # user session is hijacked.
  # @route POST /settings/change_password
  # @route_param user [old_password]
  # @route_param user [password]
  # @route_param user [password_confirmation]
  def change_password
    @user = current_user
    if @user.authenticated?(:password, params[:user][:old_password])
      if @user.update_attributes(user_params)
        if params[:user][:password].empty?
          @user.errors.add(:base, t(:password_cannot_be_blank))
        else
          flash.now[:success] = t :profile_updated
        end
      end
    else
      @user.errors.add(:base, t(:wrong_password))
    end
    render 'account'
  end

  # Renders the delete account confirmation view.
  # @route GET /settings/confirm_delete_account
  def confirm_delete_account
    @user = current_user
  end

  # Deletes the current user's account if the password is correct.
  # The password is requested to prevent acount deletion if the
  # user session is hijacked.
  # @route POST /settings/delete_account
  # @route_param user [password]
  def delete_account
    @user = current_user
    if @user.authenticated?(:password, params[:user][:password])
      log_out if logged_in?
      @user.destroy
      flash[:success] = t :account_deleted
      redirect_to root_url
    else
      @user.errors.add(:base, t(:wrong_password))
      render 'confirm_delete_account'
    end
  end

  private

    # Allowed update user parameters.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filter that confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = t :please_log_in
        redirect_to login_url
      end
    end

    # Before filter that confirms the current user has permission to alter the
    # requested user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Before filter that confirms a site admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/views/users/_settings_sidebar.html.erb
<div class="col-md-3">
  <div class="list-group">
    <a href="<%= profile_path %>" class="list-group-item <%= (selected_option == 'profile') ? 'active' : 'list-group-item-action' %>">Profile</a>
    <a href="<%= account_path %>" class="list-group-item <%= (selected_option == 'account') ? 'active' : 'list-group-item-action' %>">Account</a>
  </div>
</div>

app/views/users/_user.html.erb
<tr class="<%= user.admin ? "info" : "" %>">
  <th scope="row"><%= user.id %></th>
  <td><%= link_to user.email, user %></td>
  <td><%= user.name %></td>
  <% if !current_user?(user) %>
    <td><%= link_to "Delete", user, method: :delete, data: { confirm: "Are you sure?" } %></td>
  <% else %>
    <td></td>
  <% end %>
</tr>

app/views/users/account.html.erb
<% provide(:page_title, 'Account') %>

<% content_for :errors do %>
  <%= render 'shared/error_messages' %>
<% end %>

<% content_for :css do %>
  <%= stylesheet_link_tag 'system.css' %>
<% end %>

<script>
$.ajax({
    url: "/language-pt.json",
    type: "GET",
    contentType: 'application/json; charset=utf-8',
    success: function (resultData) {
        var locales_data = resultData;
        main(locales_data);
    },
    error: function (jqXHR, textStatus, errorThrown) {
    },
    timeout: 120000,
});

function main(locales_data){
  var gui = new Gui();
  var top_menu = new SystemGui();
  top_menu.setLocales(locales_data);
  top_menu.setSearch(false);
  top_menu.drawSystemMenu();

  var sidebar = {id:"system-sidebar",class:"system-sidebar",height:window.innerHeight-40};
  gui.addContainer(sidebar);

  var profile_button = {id:"system-profile-button",class:"system-sidebar-primary-button",top:150};
  gui.addLink(profile_button,"system-sidebar");
  gui.addText("system-profile-button","PERFIL");
  document.getElementById("system-profile-button").setAttribute('href',"/settings/profile");

  var account_button = {id:"system-account-button",class:"system-sidebar-primary-button",top:200,backgroundColor:"rgb(30,30,30)",color:"white"};
  gui.addField(account_button,"system-sidebar");
  gui.addText("system-account-button",'CONTA');

  var change_password_button = {id:"system-change-password-button",class:"system-sidebar-secondary-button-active",top:250};
  gui.addField(change_password_button,"system-sidebar");
  gui.addText("system-change-password-button","TROCAR SENHA"); // /settings/account

  var change_email_button = {id:"system-change-email-button",class:"system-sidebar-secondary-button-inactive",top:280};
  gui.addLink(change_email_button,"system-sidebar");
  gui.addText("system-change-email-button","TROCAR EMAIL");
  document.getElementById("system-change-email-button").setAttribute('href',"/email_resets/new");

  var delete_account_button = {id:"system-delete-account-button",class:"system-sidebar-secondary-button-inactive",top:310};
  gui.addLink(delete_account_button,"system-sidebar");
  gui.addText("system-delete-account-button","DELETAR CONTA");
  document.getElementById("system-delete-account-button").setAttribute('href',"/settings/confirm_delete_account");

  var rhisomas_button = {id:"system-rhisomas-button",class:"system-sidebar-primary-button",top:340};
  gui.addLink(rhisomas_button,"system-sidebar");
  gui.addText("system-rhisomas-button","RHISOMAS");
  document.getElementById("system-rhisomas-button").setAttribute('href',"/settings/rhisomas");

  var change_password_container = {id:"system-change-password",width:258,height:163,top:(window.innerHeight-225)/2,left:(window.innerWidth-320-320)/2+320,backgroundColor:"white",padding:30,border:"1px solid #aeaeae",boxshadow:"-5px 5px #aeaeae"};
  gui.addContainer(change_password_container);

  var form_label = {id:"system-label",class:"form-label",width:298};
  gui.addField(form_label,"system-change-password");
  gui.addText("system-label",'TROCAR SENHA');
  document.getElementById("system-label").style.textAlign = "center";

  var form = document.createElement("form");
  form.setAttribute('method',"post");
  form.setAttribute('action',"/settings/change_password");
  form.setAttribute('accept-charset',"UTF-8");

  var general_input = document.createElement("input");
  general_input.setAttribute('type',"hidden");
  general_input.setAttribute('name',"utf8");
  general_input.setAttribute('value',"✓");

  var auth_input = document.createElement("input");
  auth_input.setAttribute('type',"hidden");
  auth_input.setAttribute('name',"authenticity_token");
  auth_input.setAttribute('value','<%= form_authenticity_token %>');

  var old_password_input = document.createElement("input");
  old_password_input.setAttribute('type',"password");
  old_password_input.setAttribute('name',"user[password]");
  old_password_input.setAttribute('id',"user_password");
  old_password_input.setAttribute('class',"form-control");
  old_password_input.setAttribute('placeholder',"Antiga senha");

  var password_input = document.createElement("input");
  password_input.setAttribute('type',"password");
  password_input.setAttribute('name',"user[password]");
  password_input.setAttribute('id',"user_password");
  password_input.setAttribute('class',"form-control");
  password_input.setAttribute('placeholder',"Nova senha");

  var new_password_input = document.createElement("input");
  new_password_input.setAttribute('type',"password");
  new_password_input.setAttribute('name',"user[password]");
  new_password_input.setAttribute('id',"user_password");
  new_password_input.setAttribute('class',"form-control");
  new_password_input.setAttribute('placeholder',"Confirmação de senha");

  var submit_button = document.createElement("input");
  submit_button.setAttribute('type',"submit");
  submit_button.setAttribute('name',"commit");
  submit_button.setAttribute('data-disable-with',"ATUALIZAR SENHA");
  submit_button.setAttribute('class',"button-center");
  submit_button.setAttribute('id',"submit-button");
  submit_button.setAttribute('value',"ATUALIZAR SENHA");
  submit_button.style.width = document.getElementById("system-change-password").offsetWidth+"px";
  submit_button.style.left = "-1px";
  submit_button.style.top = document.getElementById("system-change-password").offsetHeight-42-1+"px";

  form.appendChild(general_input);
  form.appendChild(auth_input);
  form.appendChild(old_password_input);
  form.appendChild(password_input);
  form.appendChild(new_password_input);
  form.appendChild(submit_button);

  document.getElementById('system-change-password').appendChild(form);
}
  

</script>

app/views/users/confirm_delete_account.html.erb
<% provide(:page_title, 'Delete Account') %>

<% content_for :errors do %>
  <%= render 'shared/error_messages' %>
<% end %>

<% content_for :css do %>
  <%= stylesheet_link_tag 'system.css' %>
<% end %>

<script>
$.ajax({
    url: "/language-pt.json",
    type: "GET",
    contentType: 'application/json; charset=utf-8',
    success: function (resultData) {
        var locales_data = resultData;
        main(locales_data);
    },
    error: function (jqXHR, textStatus, errorThrown) {
    },
    timeout: 120000,
});

function main(locales_data){
  var gui = new Gui();
  var top_menu = new SystemGui();
  top_menu.setLocales(locales_data);
  top_menu.setSearch(false);
  top_menu.drawSystemMenu();

  var sidebar = {id:"system-sidebar",class:"system-sidebar",height:window.innerHeight-40};
  gui.addContainer(sidebar);

  var profile_button = {id:"system-profile-button",class:"system-sidebar-primary-button",top:150};
  gui.addLink(profile_button,"system-sidebar");
  gui.addText("system-profile-button","PERFIL");
  document.getElementById("system-profile-button").setAttribute('href',"/settings/profile");

  var account_button = {id:"system-account-button",class:"system-sidebar-primary-button",top:200,backgroundColor:"rgb(30,30,30)",color:"white"};
  gui.addField(account_button,"system-sidebar");
  gui.addText("system-account-button",'CONTA');

  var change_password_button = {id:"system-change-password-button",class:"system-sidebar-secondary-button-inactive",top:250};
  gui.addLink(change_password_button,"system-sidebar");
  gui.addText("system-change-password-button","TROCAR SENHA");
  document.getElementById("system-change-password-button").setAttribute('href',"/settings/account");

  var change_email_button = {id:"system-change-email-button",class:"system-sidebar-secondary-button-inactive",top:280};
  gui.addLink(change_email_button,"system-sidebar");
  gui.addText("system-change-email-button","TROCAR EMAIL");
  document.getElementById("system-change-email-button").setAttribute('href',"/email_resets/new");

  var delete_account_button = {id:"system-delete-account-button",class:"system-sidebar-secondary-button-active",top:310};
  gui.addField(delete_account_button,"system-sidebar");
  gui.addText("system-delete-account-button","DELETAR CONTA");

  var rhisomas_button = {id:"system-rhisomas-button",class:"system-sidebar-primary-button",top:340};
  gui.addLink(rhisomas_button,"system-sidebar");
  gui.addText("system-rhisomas-button","RHISOMAS");
  document.getElementById("system-rhisomas-button").setAttribute('href',"/settings/rhisomas");

  var delete_account_container = {id:"system-delete-account",width:258,height:98,top:(window.innerHeight-160)/2,left:(window.innerWidth-320-320)/2+320,backgroundColor:"white",padding:30,border:"1px solid #aeaeae",boxshadow:"-5px 5px #aeaeae"};
  gui.addContainer(delete_account_container);

  var form_label = {id:"system-label",class:"form-label",width:298};
  gui.addField(form_label,"system-delete-account");
  gui.addText("system-label",'DELETAR CONTA');
  document.getElementById("system-label").style.textAlign = "center";

  var form = document.createElement("form");
  form.setAttribute('method',"post");
  form.setAttribute('action',"/settings/delete_account?method=post");
  form.setAttribute('accept-charset',"UTF-8");

  var general_input = document.createElement("input");
  general_input.setAttribute('type',"hidden");
  general_input.setAttribute('name',"utf8");
  general_input.setAttribute('value',"✓");

  var auth_input = document.createElement("input");
  auth_input.setAttribute('type',"hidden");
  auth_input.setAttribute('name',"authenticity_token");
  auth_input.setAttribute('value','<%= form_authenticity_token %>');

  var password_input = document.createElement("input");
  password_input.setAttribute('type',"password");
  password_input.setAttribute('name',"user[password]");
  password_input.setAttribute('id',"user_password");
  password_input.setAttribute('class',"form-control");
  password_input.setAttribute('placeholder',"Senha");

  var submit_button = document.createElement("input");
  submit_button.setAttribute('type',"submit");
  submit_button.setAttribute('name',"commit");
  submit_button.setAttribute('data-disable-with',"DELETAR CONTA");
  submit_button.setAttribute('class',"button-right");
  submit_button.setAttribute('id',"submit-button");
  submit_button.setAttribute('value',"DELETAR CONTA");
  submit_button.style.width = document.getElementById("system-delete-account").offsetWidth+"px";
  submit_button.style.left = "-1px";
  submit_button.style.top = document.getElementById("system-delete-account").offsetHeight-42-1+"px";

  form.appendChild(general_input);
  form.appendChild(auth_input);
  form.appendChild(password_input);
  form.appendChild(submit_button);

  document.getElementById('system-delete-account').appendChild(form);
}
  

</script>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<%= will_paginate %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Users</div>
      <table class="table table-striped">
        <thead class="thead-inverse">
          <tr>
            <th>#</th>
            <th>Email</th>
            <th>Name</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          <%= render @users %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:page_title, 'Sign Up') %>

  <% content_for :css do %>
    <%= stylesheet_link_tag 'system.css' %>
  <% end %>

  <% content_for :errors do %>
    <%= render 'shared/error_messages' %>
  <% end %>


<video poster="" id="bgvid" playsinline autoplay muted loop>
<source src="https://vimeo.com/190179602/download?t=1487018092&v=631426677&s=0fc854a7108aed8d1f9a3f729f94faddbbafb0868afc2b4f2a523c54ed7d1648" type="video/mp4">
</video>

<script>
var x = '<%= @user.errors.full_messages %>';
  var gui = new Gui();

  var rhisoma_logo = {id:"system-logo",width:80,height:80,top:(window.innerHeight-230)/2-40,left:((window.innerWidth-320)/2)+((318-80)/2),backgroundColor:"transparent",zindex:10};
  gui.addField(rhisoma_logo);
  gui.addText("system-logo",'<img id="rhisoma-logo" src="<%= image_path 'logo.png' %>" width="80px" height="80px" />');

  var subscription_container = {id:"system-signup",width:258,height:168,top:(window.innerHeight-230)/2,left:(window.innerWidth-320)/2,backgroundColor:"white",padding:30,border:"1px solid #aeaeae",boxshadow:"-5px 5px #aeaeae"};
  gui.addContainer(subscription_container);

  var form_label = {id:"system-label",class:"form-label",width:298};
  gui.addField(form_label,"system-signup");
  gui.addText("system-label",globals.localize.system_menu_signup.toUpperCase());

  var form = document.createElement("form");
  form.setAttribute('method',"post");
  form.setAttribute('action',"/users");
  form.setAttribute('accept-charset',"UTF-8");

  var general_input = document.createElement("input");
  general_input.setAttribute('type',"hidden");
  general_input.setAttribute('name',"utf8");
  general_input.setAttribute('value',"✓");

  var auth_input = document.createElement("input");
  auth_input.setAttribute('type',"hidden");
  auth_input.setAttribute('name',"authenticity_token");
  auth_input.setAttribute('value','<%= form_authenticity_token %>');

  var email_input = document.createElement("input");
  email_input.setAttribute('type',"email");
  email_input.setAttribute('name',"user[email]");
  email_input.setAttribute('id',"user_email");
  email_input.setAttribute('class',"form-control");
  email_input.setAttribute('placeholder',globals.localize.system_email);

  var password_input = document.createElement("input");
  password_input.setAttribute('type',"password");
  password_input.setAttribute('name',"user[password]");
  password_input.setAttribute('id',"user_password");
  password_input.setAttribute('class',"form-control");
  password_input.setAttribute('placeholder',globals.localize.system_password);

  var password_confirmation_input = document.createElement("input");
  password_confirmation_input.setAttribute('type',"password");
  password_confirmation_input.setAttribute('name',"user[password_confirmation]");
  password_confirmation_input.setAttribute('id',"user_password_confirmation");
  password_confirmation_input.setAttribute('class',"form-control");
  password_confirmation_input.setAttribute('placeholder',globals.localize.settings_account_confirm_password);

  var submit_button = document.createElement("input");
  submit_button.setAttribute('type',"submit");
  submit_button.setAttribute('name',"commit");
  submit_button.setAttribute('data-disable-with',globals.localize.system_menu_do_signup.toUpperCase());
  submit_button.setAttribute('class',"button-right");
  submit_button.setAttribute('id',"submit-button");
  submit_button.setAttribute('value',globals.localize.system_menu_do_signup.toUpperCase());
  submit_button.style.width = document.getElementById("system-signup").offsetWidth/2+"px";
  submit_button.style.left = document.getElementById("system-signup").offsetWidth/2-1+"px";
  submit_button.style.top = document.getElementById("system-signup").offsetHeight-42-1+"px";

  form.appendChild(general_input);
  form.appendChild(auth_input);
  form.appendChild(email_input);
  form.appendChild(password_input);
  form.appendChild(password_confirmation_input);
  form.appendChild(submit_button);

  var back_button = document.createElement("a");
  back_button.setAttribute('class',"button-left");
  back_button.setAttribute('href',"/");
  back_button.innerHTML = globals.localize.system_back.toUpperCase();
  back_button.style.width = document.getElementById("system-signup").offsetWidth/2-1+"px";
  back_button.style.left = "-1px";
  back_button.style.top = document.getElementById("system-signup").offsetHeight-42-1+"px";

  document.getElementById("system-signup").appendChild(back_button);
  document.getElementById('system-signup').appendChild(form);
  

</script>

app/views/users/profile.html.erb
<% provide(:page_title, "Profile") %>
<% content_for :errors do %>
  <%= render 'shared/error_messages' %>
<% end %>

<% content_for :css do %>
  <%= stylesheet_link_tag 'system.css' %>
<% end %>

<script>
  var gui = new Gui();
  var top_menu = new SystemGui();
  top_menu.setLocales();
  top_menu.setSearch(false);
  top_menu.drawSystemMenu();
  top_menu.lockMenu();

  var sidebar = new SystemSettingsSidebar();
  sidebar.drawSidebar(1,0);
</script>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">User</div>
      <div class="panel-body">
        <dl class="dl-horizontal">
          <dt>Id<dt>
          <dd><%= @user.id %><dd>
          <dt>Email<dt>
          <dd><%= @user.email %><dd>
          <dt>Name<dt>
          <dd><%= @user.name %><dd>
        </dl>
        <div></div>
        <div><%= link_to "Voltar", users_path %></div>
      </div>
    </div>
  </div>
</div>

app/views/users/signup.html.erb
<% provide(:page_title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>