config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'about',   to: 'static_pages#about'
  get 'signup',  to: 'users#new'

  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :email_resets,        only: [:new, :create, :edit, :update]

  get  'home',                     to: 'users#home'
  scope '/settings' do
    get  'profile',                to: 'users#profile'
    get  'account',                to: 'users#account' 
    get  'confirm_delete_account', to: 'users#confirm_delete_account'
    post 'change_password',        to: 'users#change_password'
    post 'delete_account',         to: 'users#delete_account'
    get  'rhisomas',               to: 'territories#list'
    get  'edit_rhisoma/:id',       to: 'territories#edit'
  end

  resources :territories
  patch '/nodes/position', to: 'nodes#bulk_update_pos'
  resources :nodes
  resources :edges
  post '/territories/:id/clone', to: 'territories#clone'

  resources :styling_groups

  get '/.well-known/acme-challenge/:id' => 'sessions#temp'
  get '/fake_logout' => 'sessions#fake_destroy'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <nav>
      <div class="navbar-header">
        <%= link_to "Orkhestra",   root_url, class: "navbar-brand" %>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.admin ? '(admin)' : '' %> 
              <%= current_user.email %> 
              <span class="caret"></span> 
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Home', home_path %></li>
              <% if current_user.admin %>
                <li><%= link_to 'Users', users_path %></li>
              <% end %>
              <li><%= link_to 'Settings', profile_path %></li>
              <li><%= link_to 'Log out', logout_path, method: 'delete' %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:page_title)) %></title>
    <%= csrf_meta_tags %>

    <!--<%= stylesheet_link_tag    'application', media: 'all' %>-->
    <%= yield(:css) %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <%= render 'shared/globals' %>

    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <!--<%= render 'layouts/header' %>-->
    <% flash.each do |message_type, message| %>
      <div class="close-this alert alert-<%= message_type %> alert-dismissable" style="position:absolute;bottom:20%;width:100%;height:auto;text-align: center;font-family: Source Sans Pro;font-size: 14px">
        <div style="position:relative;width: 302px;margin-left: auto;margin-right: auto">
          <div class="container" style="position:absolute;margin:auto;width:300px;height:auto;text-align: center;background-color: white;color:black;border:1px solid rgb(200,60,60);padding-top: 10px;padding-bottom: 10px;box-shadow: rgb(200, 60, 60) -5px 5px">
            <%= message %>
          </div>
          <a href="javascript:close(this)" class="close" data-dismiss="alert" aria-label="close" title="close" style="position:relative;left:140px;top:-8px;font-size: 30px;text-decoration: none;color:rgb(200,60,60)">×</a>
        </div>
      </div>
      <script type="text/javascript">
        function close(element) {
          $(".close-this").remove();
        }
      </script>
    <% end %>
    <%= yield(:errors) %>

    <!-- <div class="container main"> -->
      <%= yield %>

      <!--<%= debug(params) if Rails.env.development? %>-->
  <!--   </div> -->
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:page_title)) %></title>
    <%= csrf_meta_tags %>

    <%= yield(:css) %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
    <%= render 'shared/globals' %>

    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <% flash.each do |message_type, message| %>
      <div class="close-this alert alert-<%= message_type %> alert-dismissable" style="position:absolute;bottom:20%;width:100%;height:auto;text-align: center;font-family: Source Sans Pro;font-size: 14px">
        <div style="position:relative;width: 302px;margin-left: auto;margin-right: auto">
          <div class="container" style="position:absolute;margin:auto;width:300px;height:auto;text-align: center;background-color: white;color:black;border:1px solid rgb(200,60,60);padding-top: 10px;padding-bottom: 10px;box-shadow: rgb(200, 60, 60) -5px 5px">
            <%= message %>
          </div>
          <a href="javascript:close(this)" class="close" data-dismiss="alert" aria-label="close" title="close" style="position:relative;left:140px;top:-8px;font-size: 30px;text-decoration: none;color:rgb(200,60,60)">×</a>
        </div>
      </div>
      <script type="text/javascript">
        function close(element) {
          $(".close-this").remove();
        }
      </script>
    <% end %>
    <%= yield(:errors) %>

    <%= yield %>
  </body>
</html>